FROM rocker/rstudio:latest
COPY R_requirements.R R_requirements.R
USER root
RUN apt-get update
RUN apt-get install -y --no-install-recommends coinor-cbc coinor-libcbc-dev
RUN apt-get install -y --no-install-recommends libglpk-dev
RUN R < R_requirements.R --no-save
RUN R -e 'BiocManager::install(c("decoupleR"))'
RUN apt-get install -y --no-install-recommends openjdk-8-jdk maven
RUN git clone https://github.com/PathwayAndDataAnalysis/causalpath.git && \ 
cd causalpath &&  mvn clean install && mvn assembly:single 
RUN apt-get install -y --no-install-recommends openjdk-11-jdk
RUN R -e 'BiocManager::install(c("paxtoolsr"))'
RUN chmod -R 777 /home
